### ISSUE TITLE
Final capstone project

### ISSUE THREAD

**Issue by GiuseppeTG** [ElsonOtake/Final_capstone_backend#6]
## Final Capstone, group of 4: 
- @ElsonOtake 
- @GiuseppeTG
- @AntonioHincapie
- @mgmediaweb

### Backend:
- [Link to project kanban](https://github.com/ElsonOtake/Final_capstone_backend/projects/1)
![image](https://user-images.githubusercontent.com/99298594/196814496-516da0d1-72f2-4b0c-8d40-e73d42e33782.png)

### Frontend:
- [Link to repo](https://github.com/mgmediaweb/final-capstone-frontend)

**Comment by Meltrust** [comment]
Hi @GiuseppeTG,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been assigned to someone✔️
- All cards have points 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] Please, kindly just make one Kanban board for the project, instead of 2.

## Explanation

This is one big project, which spans 2 repos.  But it is still one project.  You will need 1 link for your final presentation, and you won't be able to provide 2.  For the final capstones, it's customary to have the single Kanban board that spans all tasks on the backend repo.


## Tips and extra help

- Just merge the frontend tasks into the backend tasks so you end up with a big kanban.
- Ensure that everyone in the team gets fair and same points of work.

Cheers and Happy coding!👏👏👏



**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by AntonioHincapie** [comment]
Hi, @Meltrust

Can you please clarify this for us?

You say that we are available to put a link for our presentation, but as you can see here we are available to put two links to our two repositories. 
![image](https://user-images.githubusercontent.com/99298594/196805361-6585cba6-f830-46e7-90b2-33bf2f74dade.png)

Please can you help us with this?

**Comment by Meltrust** [comment]
> Hi, @Meltrust
> 
> Can you please clarify this for us?
> 
> You say that we are available to put a link for our presentation, but as you can see here we are available to put two links to our two repositories. ![image](https://user-images.githubusercontent.com/99298594/196805361-6585cba6-f830-46e7-90b2-33bf2f74dade.png)
> 
> Please can you help us with this?

Hi, thanks for the question.  I was referring to the kanban board itself, not the repos.  I should have worded it better.  

Aside from that, plese note that in this particular project, all the review requirements are just suggestions to ensure your success.  In the industry, we never create 2 kanban boards for a single project, even if it spans multiple repos. 

In case you follow my suggestion, you can just copy the cards from 1 project to the other (about 10 min).

I hope this helps, and makes sense to you.

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
